### ISSUE TITLE
Unable to align all page content in the center 

### ISSUE THREAD

**Issue by vivianzqq** [ShareVR/ShareVR-WebsiteDev#11]
**Description**
We need to align all page content in the center and leave more white space on both sides, just as what we already have on the live site. It looks better and people don't need to go from one end of the page to the other to see the content (we will have more texts like blog and stuff later in development, so we want to make it as user-friendly as possible for people to scan the content on our page from the beginning). 

This is an example of my ideal design: https://www.apple.com/newsroom/
Our live page looks pretty similar to this one. 
Ideally, besides our cover video and the feature icons on the landing page, everything else should be aligned in a centered container of the page. The feature icons should also be included in this container. But its background could be spread out through the page.  

Right now I use bootstrap grid for all the alignment to make sure everything is responsive. But I'm not sure whether I should hard code the alignment details, because that will probably break the responsiveness. 

I also looked into wix's code, and it doesn't look like they are using bootstrap to do this. So I'm not sure how should I proceed from here. 

**Planned Action**
Test with the showcase page to see how much white space we want to leave on both sides of the page and try to make it as the same as the live site on wix. If we are able to find a solution without break the responsiveness, then we can apply the methods to every page and make them all have the same amount of white space. 
 
**Tasks**
- [ ] Test with documentation page for content alignment 
- [ ] Apply the same alignment to the documentation page  
- [ ] Apply the same alignment to the landing page 
- [ ] Apply the same alignment to the about page

**Comment by adammy123** [comment]
sorry @vivianzqq i am not very sure what I should do here

**Comment by hwkeyser** [comment]
She wants the content to have a greater margin, similar to how the Wix page pushes the content further inward while remaining responsive. I don't know that having the extra amount of margin/padding is High-priority. but that's what she's asking for. Basically, open the wix page in one tab and the github-page in another, and flip back and forth and you'll see the github page has wider content which is closer to the edges. 

I'm thinking once we're off the wix structure we can deviate into our own designs rather than trying to perfectly match the wix templates. But that's my opinion

**Comment by hwkeyser** [comment]
fixed on new layout. no longer relevant.
