### ISSUE TITLE
Host all the videos from YouTube

### ISSUE THREAD

**Issue by chenchen2015** [ShareVR/ShareVR-WebsiteDev#21]
#### Description
It's generally a bad practice to keep static video files that we don't modify in the repository. It makes checkout and branching process take way longer than it should be.

I suggest we remove all the local videos and host all of them on YouTube. **Unlisted video** for non-public facing videos, and **public video** for general marketing videos. 

#### Planned Actions
Upload all the local video contents to YouTube with the appropriate type - public or unlisted. Then delete them in the repository.

#### TODO

- [ ] Have at least two members approve the proposal @adammy123  @hwkeyser @vivianzqq 
- [ ] Upload videos to YouTube with the appropriate type - public or unlisted
- [ ] Update the link in our html file to reference the YouTube video
- [ ] Test if all the link works
- [ ] Delete local videos

**Comment by adammy123** [comment]
@chenchen2015 agreed. let me see if the header video can be replaced with a YouTube embedment

**Comment by adammy123** [comment]
I did some initial testing with hosting the header video onto YouTube (i used the "VRMA only Sizzle" video as a replacement for the testing). Here are some problems that I faced:

1. At the start as the video loads, the grey circle will appear that indicates the loading of the video.
2. With a poor internet connection (like mine is sometimes at home), the video quality will automatically dumb down to support the connection. Hence, the quality might sometimes drop down to 480p (or even 360p??), which I guess looks terrible on out page.

Other than that, I'm still working on the alignment/formatting issues with the header video.

Let me know your thoughts!
